#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_EXT_shader_image_load_formatted : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) writeonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) writeonly buffer _12_14
{
    uvec2 _m0[];
} _14;

layout(set = 0, binding = 2, std430) writeonly buffer _16_18
{
    uint _m0[];
} _18;

layout(set = 0, binding = 3) uniform image1D _22;
layout(set = 0, binding = 4) uniform image2D _25;
layout(set = 0, binding = 5) uniform image3D _28;
layout(set = 0, binding = 6) uniform image3D _29;

void main()
{
    uint _46 = (packHalf2x16(vec2(46.5, 0.0)) << 16u) | packHalf2x16(vec2(45.5, 0.0));
    f16vec2 _55 = atomicAdd(_18._m0[4u], f16vec2(unpackHalf2x16(_46)));
    _9._m0[100u] = packHalf2x16(vec2(_55));
    f16vec2 _67 = imageAtomicAdd(_22, int(5u), f16vec2(unpackHalf2x16(_46)));
    _9._m0[101u] = packHalf2x16(vec2(_67));
    f16vec2 _78 = imageAtomicAdd(_25, ivec2(uvec2(6u, 7u)), f16vec2(unpackHalf2x16(_46)));
    _9._m0[102u] = packHalf2x16(vec2(_78));
    f16vec2 _91 = imageAtomicAdd(_28, ivec3(uvec3(8u, 9u, 10u)), f16vec2(unpackHalf2x16(_46)));
    _9._m0[103u] = packHalf2x16(vec2(_91));
    f16vec2 _116 = imageAtomicAdd(_29, ivec3(uvec3(16u, 9u, 10u)), f16vec2(unpackHalf2x16((packHalf2x16(vec2(79.0, 0.0)) << 16u) | packHalf2x16(vec2(78.0, 0.0)))));
    f16vec2 _124 = imageAtomicAdd(_29, ivec3(uvec3(17u, 9u, 10u)), f16vec2(unpackHalf2x16((packHalf2x16(vec2(81.0, 0.0)) << 16u) | packHalf2x16(vec2(80.0, 0.0)))));
    _14._m0[102u] = uvec2(packHalf2x16(vec2(_116)), packHalf2x16(vec2(_124)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 132
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Image1D
OpCapability StorageImageExtendedFormats
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%35 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %16 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 1
OpDecorate %14 NonReadable
OpDecorate %15 ArrayStride 4
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %18 DescriptorSet 0
OpDecorate %18 Binding 2
OpDecorate %18 NonReadable
OpDecorate %22 DescriptorSet 0
OpDecorate %22 Binding 3
OpDecorate %22 NonReadable
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 4
OpDecorate %25 NonReadable
OpDecorate %28 DescriptorSet 0
OpDecorate %28 Binding 5
OpDecorate %28 NonReadable
OpDecorate %29 DescriptorSet 0
OpDecorate %29 Binding 6
OpDecorate %29 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeRuntimeArray %5
%16 = OpTypeStruct %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeFloat 32
%20 = OpTypeImage %19 1D 0 0 0 2 Unknown
%21 = OpTypePointer UniformConstant %20
%22 = OpVariable %21 UniformConstant
%23 = OpTypeImage %19 2D 0 0 0 2 Unknown
%24 = OpTypePointer UniformConstant %23
%25 = OpVariable %24 UniformConstant
%26 = OpTypeImage %19 3D 0 0 0 2 Unknown
%27 = OpTypePointer UniformConstant %26
%28 = OpVariable %27 UniformConstant
%29 = OpVariable %27 UniformConstant
%36 = OpConstant %19 46.5
%38 = OpConstant %19 0
%39 = OpTypeVector %19 2
%42 = OpConstant %5 16
%43 = OpConstant %19 45.5
%47 = OpTypeFloat 16
%48 = OpTypeVector %47 2
%49 = OpConstant %5 4
%50 = OpTypePointer StorageBuffer %48
%52 = OpConstant %5 0
%56 = OpConstant %5 1
%59 = OpConstant %5 100
%60 = OpTypePointer StorageBuffer %5
%62 = OpConstant %5 5
%63 = OpTypePointer Image %48
%70 = OpConstant %5 101
%72 = OpConstant %5 6
%73 = OpConstant %5 7
%81 = OpConstant %5 102
%83 = OpConstant %5 8
%84 = OpConstant %5 9
%85 = OpConstant %5 10
%86 = OpTypeVector %5 3
%94 = OpConstant %5 103
%96 = OpConstant %19 79
%100 = OpConstant %19 78
%104 = OpConstant %19 81
%108 = OpConstant %19 80
%119 = OpConstant %5 17
%128 = OpTypePointer StorageBuffer %10
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %130
%130 = OpLabel
%30 = OpLoad %26 %29
%31 = OpLoad %26 %28
%32 = OpLoad %23 %25
%33 = OpLoad %20 %22
%40 = OpCompositeConstruct %39 %36 %38
%37 = OpExtInst %5 %35 PackHalf2x16 %40
%41 = OpShiftLeftLogical %5 %37 %42
%45 = OpCompositeConstruct %39 %43 %38
%44 = OpExtInst %5 %35 PackHalf2x16 %45
%46 = OpBitwiseOr %5 %41 %44
%51 = OpAccessChain %50 %18 %52 %49
%53 = OpExtInst %39 %35 UnpackHalf2x16 %46
%54 = OpFConvert %48 %53
%55 = OpAtomicFAddEXT %48 %51 %56 %52 %54
%57 = OpFConvert %39 %55
%58 = OpExtInst %5 %35 PackHalf2x16 %57
%61 = OpAccessChain %60 %9 %52 %59
OpStore %61 %58
%64 = OpImageTexelPointer %63 %22 %62 %52
%65 = OpExtInst %39 %35 UnpackHalf2x16 %46
%66 = OpFConvert %48 %65
%67 = OpAtomicFAddEXT %48 %64 %56 %52 %66
%68 = OpFConvert %39 %67
%69 = OpExtInst %5 %35 PackHalf2x16 %68
%71 = OpAccessChain %60 %9 %52 %70
OpStore %71 %69
%74 = OpCompositeConstruct %10 %72 %73
%75 = OpImageTexelPointer %63 %25 %74 %52
%76 = OpExtInst %39 %35 UnpackHalf2x16 %46
%77 = OpFConvert %48 %76
%78 = OpAtomicFAddEXT %48 %75 %56 %52 %77
%79 = OpFConvert %39 %78
%80 = OpExtInst %5 %35 PackHalf2x16 %79
%82 = OpAccessChain %60 %9 %52 %81
OpStore %82 %80
%87 = OpCompositeConstruct %86 %83 %84 %85
%88 = OpImageTexelPointer %63 %28 %87 %52
%89 = OpExtInst %39 %35 UnpackHalf2x16 %46
%90 = OpFConvert %48 %89
%91 = OpAtomicFAddEXT %48 %88 %56 %52 %90
%92 = OpFConvert %39 %91
%93 = OpExtInst %5 %35 PackHalf2x16 %92
%95 = OpAccessChain %60 %9 %52 %94
OpStore %95 %93
%98 = OpCompositeConstruct %39 %96 %38
%97 = OpExtInst %5 %35 PackHalf2x16 %98
%99 = OpShiftLeftLogical %5 %97 %42
%102 = OpCompositeConstruct %39 %100 %38
%101 = OpExtInst %5 %35 PackHalf2x16 %102
%103 = OpBitwiseOr %5 %99 %101
%106 = OpCompositeConstruct %39 %104 %38
%105 = OpExtInst %5 %35 PackHalf2x16 %106
%107 = OpShiftLeftLogical %5 %105 %42
%110 = OpCompositeConstruct %39 %108 %38
%109 = OpExtInst %5 %35 PackHalf2x16 %110
%111 = OpBitwiseOr %5 %107 %109
%112 = OpCompositeConstruct %86 %42 %84 %85
%113 = OpImageTexelPointer %63 %29 %112 %52
%114 = OpExtInst %39 %35 UnpackHalf2x16 %103
%115 = OpFConvert %48 %114
%116 = OpAtomicFAddEXT %48 %113 %56 %52 %115
%117 = OpFConvert %39 %116
%118 = OpExtInst %5 %35 PackHalf2x16 %117
%120 = OpCompositeConstruct %86 %119 %84 %85
%121 = OpImageTexelPointer %63 %29 %120 %52
%122 = OpExtInst %39 %35 UnpackHalf2x16 %111
%123 = OpFConvert %48 %122
%124 = OpAtomicFAddEXT %48 %121 %56 %52 %123
%125 = OpFConvert %39 %124
%126 = OpExtInst %5 %35 PackHalf2x16 %125
%127 = OpCompositeConstruct %10 %118 %126
%129 = OpAccessChain %128 %14 %52 %81
OpStore %129 %127
OpReturn
OpFunctionEnd
#endif
