#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_atomic_float : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) writeonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) writeonly buffer _12_14
{
    uvec2 _m0[];
} _14;

layout(set = 0, binding = 2, rg16f) uniform image1D _18;
layout(set = 0, binding = 3, rg16f) uniform image2D _21;
layout(set = 0, binding = 4, rg16f) uniform image3D _24;
layout(set = 0, binding = 5, rg16f) uniform image3D _25;

void main()
{
    uint _42 = (packHalf2x16(vec2(46.5, 0.0)) << 16u) | packHalf2x16(vec2(45.5, 0.0));
    f16vec2 _51 = imageAtomicAdd(_18, int(5u), f16vec2(unpackHalf2x16(_42)));
    _9._m0[101u] = packHalf2x16(vec2(_51));
    f16vec2 _64 = imageAtomicAdd(_21, ivec2(uvec2(6u, 7u)), f16vec2(unpackHalf2x16(_42)));
    _9._m0[102u] = packHalf2x16(vec2(_64));
    f16vec2 _77 = imageAtomicAdd(_24, ivec3(uvec3(8u, 9u, 10u)), f16vec2(unpackHalf2x16(_42)));
    _9._m0[103u] = packHalf2x16(vec2(_77));
    f16vec2 _102 = imageAtomicAdd(_25, ivec3(uvec3(16u, 9u, 10u)), f16vec2(unpackHalf2x16((packHalf2x16(vec2(79.0, 0.0)) << 16u) | packHalf2x16(vec2(78.0, 0.0)))));
    f16vec2 _110 = imageAtomicAdd(_25, ivec3(uvec3(17u, 9u, 10u)), f16vec2(unpackHalf2x16((packHalf2x16(vec2(81.0, 0.0)) << 16u) | packHalf2x16(vec2(80.0, 0.0)))));
    _14._m0[102u] = uvec2(packHalf2x16(vec2(_102)), packHalf2x16(vec2(_110)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 118
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Image1D
OpCapability StorageImageExtendedFormats
OpCapability DenormPreserve
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%31 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 1
OpDecorate %14 NonReadable
OpDecorate %18 DescriptorSet 0
OpDecorate %18 Binding 2
OpDecorate %18 NonReadable
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 3
OpDecorate %21 NonReadable
OpDecorate %24 DescriptorSet 0
OpDecorate %24 Binding 4
OpDecorate %24 NonReadable
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 5
OpDecorate %25 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeFloat 32
%16 = OpTypeImage %15 1D 0 0 0 2 Rg16f
%17 = OpTypePointer UniformConstant %16
%18 = OpVariable %17 UniformConstant
%19 = OpTypeImage %15 2D 0 0 0 2 Rg16f
%20 = OpTypePointer UniformConstant %19
%21 = OpVariable %20 UniformConstant
%22 = OpTypeImage %15 3D 0 0 0 2 Rg16f
%23 = OpTypePointer UniformConstant %22
%24 = OpVariable %23 UniformConstant
%25 = OpVariable %23 UniformConstant
%32 = OpConstant %15 46.5
%34 = OpConstant %15 0
%35 = OpTypeVector %15 2
%38 = OpConstant %5 16
%39 = OpConstant %15 45.5
%43 = OpTypeFloat 16
%44 = OpTypeVector %43 2
%45 = OpConstant %5 5
%46 = OpTypePointer Image %44
%48 = OpConstant %5 0
%52 = OpConstant %5 1
%55 = OpConstant %5 101
%56 = OpTypePointer StorageBuffer %5
%58 = OpConstant %5 6
%59 = OpConstant %5 7
%67 = OpConstant %5 102
%69 = OpConstant %5 8
%70 = OpConstant %5 9
%71 = OpConstant %5 10
%72 = OpTypeVector %5 3
%80 = OpConstant %5 103
%82 = OpConstant %15 79
%86 = OpConstant %15 78
%90 = OpConstant %15 81
%94 = OpConstant %15 80
%105 = OpConstant %5 17
%114 = OpTypePointer StorageBuffer %10
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %116
%116 = OpLabel
%26 = OpLoad %22 %25
%27 = OpLoad %22 %24
%28 = OpLoad %19 %21
%29 = OpLoad %16 %18
%36 = OpCompositeConstruct %35 %32 %34
%33 = OpExtInst %5 %31 PackHalf2x16 %36
%37 = OpShiftLeftLogical %5 %33 %38
%41 = OpCompositeConstruct %35 %39 %34
%40 = OpExtInst %5 %31 PackHalf2x16 %41
%42 = OpBitwiseOr %5 %37 %40
%47 = OpImageTexelPointer %46 %18 %45 %48
%49 = OpExtInst %35 %31 UnpackHalf2x16 %42
%50 = OpFConvert %44 %49
%51 = OpAtomicFAddEXT %44 %47 %52 %48 %50
%53 = OpFConvert %35 %51
%54 = OpExtInst %5 %31 PackHalf2x16 %53
%57 = OpAccessChain %56 %9 %48 %55
OpStore %57 %54
%60 = OpCompositeConstruct %10 %58 %59
%61 = OpImageTexelPointer %46 %21 %60 %48
%62 = OpExtInst %35 %31 UnpackHalf2x16 %42
%63 = OpFConvert %44 %62
%64 = OpAtomicFAddEXT %44 %61 %52 %48 %63
%65 = OpFConvert %35 %64
%66 = OpExtInst %5 %31 PackHalf2x16 %65
%68 = OpAccessChain %56 %9 %48 %67
OpStore %68 %66
%73 = OpCompositeConstruct %72 %69 %70 %71
%74 = OpImageTexelPointer %46 %24 %73 %48
%75 = OpExtInst %35 %31 UnpackHalf2x16 %42
%76 = OpFConvert %44 %75
%77 = OpAtomicFAddEXT %44 %74 %52 %48 %76
%78 = OpFConvert %35 %77
%79 = OpExtInst %5 %31 PackHalf2x16 %78
%81 = OpAccessChain %56 %9 %48 %80
OpStore %81 %79
%84 = OpCompositeConstruct %35 %82 %34
%83 = OpExtInst %5 %31 PackHalf2x16 %84
%85 = OpShiftLeftLogical %5 %83 %38
%88 = OpCompositeConstruct %35 %86 %34
%87 = OpExtInst %5 %31 PackHalf2x16 %88
%89 = OpBitwiseOr %5 %85 %87
%92 = OpCompositeConstruct %35 %90 %34
%91 = OpExtInst %5 %31 PackHalf2x16 %92
%93 = OpShiftLeftLogical %5 %91 %38
%96 = OpCompositeConstruct %35 %94 %34
%95 = OpExtInst %5 %31 PackHalf2x16 %96
%97 = OpBitwiseOr %5 %93 %95
%98 = OpCompositeConstruct %72 %38 %70 %71
%99 = OpImageTexelPointer %46 %25 %98 %48
%100 = OpExtInst %35 %31 UnpackHalf2x16 %89
%101 = OpFConvert %44 %100
%102 = OpAtomicFAddEXT %44 %99 %52 %48 %101
%103 = OpFConvert %35 %102
%104 = OpExtInst %5 %31 PackHalf2x16 %103
%106 = OpCompositeConstruct %72 %105 %70 %71
%107 = OpImageTexelPointer %46 %25 %106 %48
%108 = OpExtInst %35 %31 UnpackHalf2x16 %97
%109 = OpFConvert %44 %108
%110 = OpAtomicFAddEXT %44 %107 %52 %48 %109
%111 = OpFConvert %35 %110
%112 = OpExtInst %5 %31 PackHalf2x16 %111
%113 = OpCompositeConstruct %10 %104 %112
%115 = OpAccessChain %114 %14 %48 %67
OpStore %115 %113
OpReturn
OpFunctionEnd
#endif
