#version 460
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_KHR_shader_subgroup_shuffle_relative : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) writeonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) writeonly buffer _12_14
{
    uvec2 _m0[];
} _14;

layout(set = 0, binding = 2, std430) writeonly buffer _17_19
{
    uvec4 _m0[];
} _19;

void main()
{
    _9._m0[gl_GlobalInvocationID.x] = subgroupShuffle(gl_GlobalInvocationID.x, 9u);
    _14._m0[gl_GlobalInvocationID.x + 1u] = uvec2(subgroupShuffle(gl_GlobalInvocationID.x + 1u, 9u), subgroupShuffle(gl_GlobalInvocationID.x + 2u, 9u));
    _19._m0[gl_GlobalInvocationID.x + 1u] = uvec4(subgroupShuffle(gl_GlobalInvocationID.x + 3u, 9u), subgroupShuffle(gl_GlobalInvocationID.x + 4u, 9u), subgroupShuffle(gl_GlobalInvocationID.x + 5u, 9u), subgroupShuffle(gl_GlobalInvocationID.x + 6u, 9u));
    _9._m0[gl_GlobalInvocationID.x + 2u] = subgroupShuffleUp(gl_GlobalInvocationID.x + 7u, 2u);
    _9._m0[gl_GlobalInvocationID.x + 3u] = subgroupShuffleDown(gl_GlobalInvocationID.x + 8u, 3u);
    _9._m0[gl_GlobalInvocationID.x + 4u] = subgroupShuffleXor(gl_GlobalInvocationID.x + 9u, 4u);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 74
; Schema: 0
OpCapability Shader
OpCapability GroupNonUniformShuffle
OpCapability GroupNonUniformShuffleRelative
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %23
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %17 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 1
OpDecorate %14 NonReadable
OpDecorate %16 ArrayStride 16
OpMemberDecorate %17 0 Offset 0
OpDecorate %17 Block
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 2
OpDecorate %19 NonReadable
OpDecorate %23 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 4
%16 = OpTypeRuntimeArray %15
%17 = OpTypeStruct %16
%18 = OpTypePointer StorageBuffer %17
%19 = OpVariable %18 StorageBuffer
%21 = OpTypeVector %5 3
%22 = OpTypePointer Input %21
%23 = OpVariable %22 Input
%24 = OpTypePointer Input %5
%26 = OpConstant %5 0
%28 = OpConstant %5 9
%30 = OpConstant %5 3
%31 = OpTypePointer StorageBuffer %5
%34 = OpConstant %5 1
%36 = OpConstant %5 2
%41 = OpTypePointer StorageBuffer %10
%45 = OpConstant %5 4
%47 = OpConstant %5 5
%49 = OpConstant %5 6
%56 = OpTypePointer StorageBuffer %15
%59 = OpConstant %5 7
%64 = OpConstant %5 8
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %72
%72 = OpLabel
%25 = OpAccessChain %24 %23 %26
%27 = OpLoad %5 %25
%29 = OpGroupNonUniformShuffle %5 %30 %27 %28
%32 = OpAccessChain %31 %9 %26 %27
OpStore %32 %29
%33 = OpIAdd %5 %27 %34
%35 = OpIAdd %5 %27 %36
%37 = OpGroupNonUniformShuffle %5 %30 %33 %28
%38 = OpGroupNonUniformShuffle %5 %30 %35 %28
%39 = OpIAdd %5 %27 %34
%40 = OpCompositeConstruct %10 %37 %38
%42 = OpAccessChain %41 %14 %26 %39
OpStore %42 %40
%43 = OpIAdd %5 %27 %30
%44 = OpIAdd %5 %27 %45
%46 = OpIAdd %5 %27 %47
%48 = OpIAdd %5 %27 %49
%50 = OpGroupNonUniformShuffle %5 %30 %43 %28
%51 = OpGroupNonUniformShuffle %5 %30 %44 %28
%52 = OpGroupNonUniformShuffle %5 %30 %46 %28
%53 = OpGroupNonUniformShuffle %5 %30 %48 %28
%54 = OpIAdd %5 %27 %34
%55 = OpCompositeConstruct %15 %50 %51 %52 %53
%57 = OpAccessChain %56 %19 %26 %54
OpStore %57 %55
%58 = OpIAdd %5 %27 %59
%60 = OpGroupNonUniformShuffleUp %5 %30 %58 %36
%61 = OpIAdd %5 %27 %36
%62 = OpAccessChain %31 %9 %26 %61
OpStore %62 %60
%63 = OpIAdd %5 %27 %64
%65 = OpGroupNonUniformShuffleDown %5 %30 %63 %30
%66 = OpIAdd %5 %27 %30
%67 = OpAccessChain %31 %9 %26 %66
OpStore %67 %65
%68 = OpIAdd %5 %27 %28
%69 = OpGroupNonUniformShuffleXor %5 %30 %68 %45
%70 = OpIAdd %5 %27 %45
%71 = OpAccessChain %31 %9 %26 %70
OpStore %71 %69
OpReturn
OpFunctionEnd
#endif
