#version 460
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) writeonly buffer SSBO
{
    uint _m0[];
} _9;

void main()
{
    _9._m0[gl_GlobalInvocationID.x] = subgroupAny(gl_GlobalInvocationID.x != 0u) ? 4294967295u : 0u;
    _9._m0[gl_GlobalInvocationID.x + 3u] = subgroupAll(gl_GlobalInvocationID.x != 0u) ? 4294967295u : 0u;
    _9._m0[gl_GlobalInvocationID.x + 4u] = subgroupBallot(gl_GlobalInvocationID.x != 0u).x;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 42
; Schema: 0
OpCapability Shader
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformBallot
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %13
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %13 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%11 = OpTypeVector %5 3
%12 = OpTypePointer Input %11
%13 = OpVariable %12 Input
%14 = OpTypePointer Input %5
%16 = OpConstant %5 0
%18 = OpTypeBool
%21 = OpConstant %5 3
%23 = OpConstant %5 4294967295
%24 = OpTypePointer StorageBuffer %5
%32 = OpTypeVector %5 4
%37 = OpConstant %5 4
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %40
%40 = OpLabel
%15 = OpAccessChain %14 %13 %16
%17 = OpLoad %5 %15
%19 = OpINotEqual %18 %17 %16
%20 = OpGroupNonUniformAny %18 %21 %19
%22 = OpSelect %5 %20 %23 %16
%25 = OpAccessChain %24 %9 %16 %17
OpStore %25 %22
%26 = OpINotEqual %18 %17 %16
%27 = OpGroupNonUniformAll %18 %21 %26
%28 = OpSelect %5 %27 %23 %16
%29 = OpIAdd %5 %17 %21
%30 = OpIAdd %5 %17 %21
%31 = OpAccessChain %24 %9 %16 %30
OpStore %31 %28
%33 = OpINotEqual %18 %17 %16
%34 = OpGroupNonUniformBallot %32 %21 %33
%35 = OpCompositeExtract %5 %34 0
%36 = OpIAdd %5 %17 %37
%38 = OpIAdd %5 %17 %37
%39 = OpAccessChain %24 %9 %16 %38
OpStore %39 %35
OpReturn
OpFunctionEnd
#endif
